### ISSUE TITLE
Reading from certain processes

### ISSUE THREAD

**Issue by KingLycosa** [Exaphis/Tsunami#2]
I have a game that is protected by EAC that can be launched with or without EAC, when EAC is launched the driver cannot read the memory of the process however when it is launched without it it can read the processes memory. Any idea why this is? Not sure if thats what this project is meant to achieve but I did see an unknowncheats reference so I assumed so.

**Comment by KingLycosa** [comment]
(Keep in mind these are the exact same address exact same code, the only difference is when EAC is loaded it throws an exception)

**Comment by KingLycosa** [comment]
with EAC

![image](https://user-images.githubusercontent.com/9650601/53291151-86e2e580-377c-11e9-922e-180a3ef29005.png)

with EAC
![image](https://user-images.githubusercontent.com/9650601/53291160-c27daf80-377c-11e9-90a5-df1efcdfce02.png)

**Comment by Exaphis** [comment]
Interesting, I haven't tried this in a game w/ EAC yet. Any chance you could build the driver with ```#define DEBUG``` at the top and see what is outputted with Dbgview?

**Comment by Exaphis** [comment]
Just realized it's not throwing a read exception which means the driver should think it succeeded. I'll have to look into this further.

**Comment by KingLycosa** [comment]
[+] Write request received.
PID: 5944, address: 0x8FFBCC, size: 4 
 [+] Waiting for request event..

[+] Read request received.
PID: 4896, address: 0x8FFBCC, size: 4 
[-] CopyVirtualMemory failed. Status: 00000000C0000141
 


The first process is without EAC the second is with. 

the only thing I can think of is that its how I am getting the process base with getmodule, but im not sure...

**Comment by KingLycosa** [comment]
I am leaving now for about 10 hours, I will attempt to reply but probably wont be able to. The issue is probably in my code.

**Comment by Exaphis** [comment]
By the looks of it EAC is somehow blocking MmSecureVirtualMemory. I'll look into this.

**Comment by KingLycosa** [comment]
Yeah, so looking at my code once more I don't see what else I can change. I don't think I actually need to pass the base being this is reading virtual memory and the base should just be 0, correct?

I tried with and without base and the same result happened.

**Comment by KingLycosa** [comment]
I was reading on MmSecureVirtualMemory and from what I gather it stops another process (or driver in this case) from changing the access rights of a memory region?

So my thinking is that maybe EAC just realizes some other driver is protecting this range and blocks it? Not really sure honestly. Gonna look into changing the method of reading / writing

**Comment by Exaphis** [comment]
Let me know if you make any progress. The purpose of MmSecureVirtualMemory there is to make sure the memory region does not suddenly become unreadable/unwritable which would cause a bugcheck at RtlCopyMemory. I'm unable to use structured exception handling there because TDL/drvmap doesn't support it.

**Comment by Exaphis** [comment]
Maybe try replacing the reading/writing with MmCopyVirtualMemory.

**Comment by KingLycosa** [comment]
It must be my code... I just tried it with MmCopyVirtualMemory and it still is giving me the same error...

**Comment by Exaphis** [comment]
What game is this?

**Comment by KingLycosa** [comment]
DeadbyDaylight, however I have tried on 2 other EAC games same problem... I think that the problem is that returning the process base from userland causes problems. I have been trying to make a GetModule function to return a modules base from ring0

**Comment by Exaphis** [comment]
Just implemented getting a module's base address from kernel mode in commit https://github.com/Exaphis/Tsunami/commit/478e66f36df371cb28607353891394a15aa93b3f. Let me know if this fixes your issue.

**Comment by KingLycosa** [comment]
![image](https://user-images.githubusercontent.com/9650601/53307042-25954200-3862-11e9-95c3-19fde8a61c8f.png)

![image](https://user-images.githubusercontent.com/9650601/53307064-6a20dd80-3862-11e9-991b-82b0f6a0553d.png)

Both EAC process and Usermode process get the same error, Also tried just grabbing kernel32.dll and it sends same error.

I know the userland is able to read the shared memory because I cna still read / write to the user process...

![image](https://user-images.githubusercontent.com/9650601/53307099-e5828f00-3862-11e9-902e-b7be916da50c.png)

I think maybe it has something to do with the size of things being sent to driver. I am still researching but I have gotten it to read from the process successfully once however it gave me a wrong value

**Comment by Exaphis** [comment]
I can't seem to replicate this error, GetModuleBase works perfectly for me.

**Comment by KingLycosa** [comment]
After getting the error above the driver also stops responding to any requests. Figuring the driver unloaded itself I attempted to reload and got 
![image](https://user-images.githubusercontent.com/9650601/53309345-5af75b00-3875-11e9-955c-fb9e888decfa.png)

I am not sure what is causing this because pulling the previous commit works perfectly.

Here is my winver, check if it matches yours.
![image](https://user-images.githubusercontent.com/9650601/53309324-39966f00-3875-11e9-8d20-d4bc93b7b692.png)

**Comment by Exaphis** [comment]
I don't think the driver unloaded itself because the status is STATUS_OBJECT_NAME_COLLISION, meaning the section wasn't closed. I'm currently on version 1709.

**Comment by KingLycosa** [comment]
Yer I realize, my picture popped below the text instead of next it so the wording was a bit confusing. I think that maybe it is a problem with the newer version of windows. No reason it shouldn't be working from the repo with no modification. I will look into a cross version fix and hopefully this solves my problem with reading. It is weird because in my own project I am using MmCopyVirtualMemory and it is reading from the process just fine...

**Comment by Exaphis** [comment]
Just tested on version 1809, GetModuleBase, Read, and Write worked on a dummy process.

**Comment by KingLycosa** [comment]
solved by compiling in release... Yes the get module fixed it
